
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Direction = {
  up: 'up',
  down: 'down'
} as const

export type Direction = (typeof Direction)[keyof typeof Direction]
