
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ausleihen` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Ausleihen
 * 
 */
export type AusleihenModel = runtime.Types.Result.DefaultSelection<Prisma.$AusleihenPayload>

export type AggregateAusleihen = {
  _count: AusleihenCountAggregateOutputType | null
  _avg: AusleihenAvgAggregateOutputType | null
  _sum: AusleihenSumAggregateOutputType | null
  _min: AusleihenMinAggregateOutputType | null
  _max: AusleihenMaxAggregateOutputType | null
}

export type AusleihenAvgAggregateOutputType = {
  kunde_id: number | null
  exemplar_id: number | null
}

export type AusleihenSumAggregateOutputType = {
  kunde_id: number | null
  exemplar_id: number | null
}

export type AusleihenMinAggregateOutputType = {
  kunde_id: number | null
  exemplar_id: number | null
  ausleihdatum: Date | null
  rueckgabedatum: Date | null
}

export type AusleihenMaxAggregateOutputType = {
  kunde_id: number | null
  exemplar_id: number | null
  ausleihdatum: Date | null
  rueckgabedatum: Date | null
}

export type AusleihenCountAggregateOutputType = {
  kunde_id: number
  exemplar_id: number
  ausleihdatum: number
  rueckgabedatum: number
  _all: number
}


export type AusleihenAvgAggregateInputType = {
  kunde_id?: true
  exemplar_id?: true
}

export type AusleihenSumAggregateInputType = {
  kunde_id?: true
  exemplar_id?: true
}

export type AusleihenMinAggregateInputType = {
  kunde_id?: true
  exemplar_id?: true
  ausleihdatum?: true
  rueckgabedatum?: true
}

export type AusleihenMaxAggregateInputType = {
  kunde_id?: true
  exemplar_id?: true
  ausleihdatum?: true
  rueckgabedatum?: true
}

export type AusleihenCountAggregateInputType = {
  kunde_id?: true
  exemplar_id?: true
  ausleihdatum?: true
  rueckgabedatum?: true
  _all?: true
}

export type AusleihenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ausleihen to aggregate.
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ausleihens to fetch.
   */
  orderBy?: Prisma.AusleihenOrderByWithRelationInput | Prisma.AusleihenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AusleihenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ausleihens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ausleihens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Ausleihens
  **/
  _count?: true | AusleihenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AusleihenAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AusleihenSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AusleihenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AusleihenMaxAggregateInputType
}

export type GetAusleihenAggregateType<T extends AusleihenAggregateArgs> = {
      [P in keyof T & keyof AggregateAusleihen]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAusleihen[P]>
    : Prisma.GetScalarType<T[P], AggregateAusleihen[P]>
}




export type AusleihenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AusleihenWhereInput
  orderBy?: Prisma.AusleihenOrderByWithAggregationInput | Prisma.AusleihenOrderByWithAggregationInput[]
  by: Prisma.AusleihenScalarFieldEnum[] | Prisma.AusleihenScalarFieldEnum
  having?: Prisma.AusleihenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AusleihenCountAggregateInputType | true
  _avg?: AusleihenAvgAggregateInputType
  _sum?: AusleihenSumAggregateInputType
  _min?: AusleihenMinAggregateInputType
  _max?: AusleihenMaxAggregateInputType
}

export type AusleihenGroupByOutputType = {
  kunde_id: number
  exemplar_id: number
  ausleihdatum: Date
  rueckgabedatum: Date | null
  _count: AusleihenCountAggregateOutputType | null
  _avg: AusleihenAvgAggregateOutputType | null
  _sum: AusleihenSumAggregateOutputType | null
  _min: AusleihenMinAggregateOutputType | null
  _max: AusleihenMaxAggregateOutputType | null
}

type GetAusleihenGroupByPayload<T extends AusleihenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AusleihenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AusleihenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AusleihenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AusleihenGroupByOutputType[P]>
      }
    >
  >



export type AusleihenWhereInput = {
  AND?: Prisma.AusleihenWhereInput | Prisma.AusleihenWhereInput[]
  OR?: Prisma.AusleihenWhereInput[]
  NOT?: Prisma.AusleihenWhereInput | Prisma.AusleihenWhereInput[]
  kunde_id?: Prisma.IntFilter<"Ausleihen"> | number
  exemplar_id?: Prisma.IntFilter<"Ausleihen"> | number
  ausleihdatum?: Prisma.DateTimeFilter<"Ausleihen"> | Date | string
  rueckgabedatum?: Prisma.DateTimeNullableFilter<"Ausleihen"> | Date | string | null
  kunde?: Prisma.XOR<Prisma.KundeScalarRelationFilter, Prisma.KundeWhereInput>
  exemplar?: Prisma.XOR<Prisma.ExemplarScalarRelationFilter, Prisma.ExemplarWhereInput>
}

export type AusleihenOrderByWithRelationInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
  ausleihdatum?: Prisma.SortOrder
  rueckgabedatum?: Prisma.SortOrderInput | Prisma.SortOrder
  kunde?: Prisma.KundeOrderByWithRelationInput
  exemplar?: Prisma.ExemplarOrderByWithRelationInput
}

export type AusleihenWhereUniqueInput = Prisma.AtLeast<{
  kunde_id_exemplar_id?: Prisma.AusleihenKunde_idExemplar_idCompoundUniqueInput
  AND?: Prisma.AusleihenWhereInput | Prisma.AusleihenWhereInput[]
  OR?: Prisma.AusleihenWhereInput[]
  NOT?: Prisma.AusleihenWhereInput | Prisma.AusleihenWhereInput[]
  kunde_id?: Prisma.IntFilter<"Ausleihen"> | number
  exemplar_id?: Prisma.IntFilter<"Ausleihen"> | number
  ausleihdatum?: Prisma.DateTimeFilter<"Ausleihen"> | Date | string
  rueckgabedatum?: Prisma.DateTimeNullableFilter<"Ausleihen"> | Date | string | null
  kunde?: Prisma.XOR<Prisma.KundeScalarRelationFilter, Prisma.KundeWhereInput>
  exemplar?: Prisma.XOR<Prisma.ExemplarScalarRelationFilter, Prisma.ExemplarWhereInput>
}, "kunde_id_exemplar_id">

export type AusleihenOrderByWithAggregationInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
  ausleihdatum?: Prisma.SortOrder
  rueckgabedatum?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AusleihenCountOrderByAggregateInput
  _avg?: Prisma.AusleihenAvgOrderByAggregateInput
  _max?: Prisma.AusleihenMaxOrderByAggregateInput
  _min?: Prisma.AusleihenMinOrderByAggregateInput
  _sum?: Prisma.AusleihenSumOrderByAggregateInput
}

export type AusleihenScalarWhereWithAggregatesInput = {
  AND?: Prisma.AusleihenScalarWhereWithAggregatesInput | Prisma.AusleihenScalarWhereWithAggregatesInput[]
  OR?: Prisma.AusleihenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AusleihenScalarWhereWithAggregatesInput | Prisma.AusleihenScalarWhereWithAggregatesInput[]
  kunde_id?: Prisma.IntWithAggregatesFilter<"Ausleihen"> | number
  exemplar_id?: Prisma.IntWithAggregatesFilter<"Ausleihen"> | number
  ausleihdatum?: Prisma.DateTimeWithAggregatesFilter<"Ausleihen"> | Date | string
  rueckgabedatum?: Prisma.DateTimeNullableWithAggregatesFilter<"Ausleihen"> | Date | string | null
}

export type AusleihenCreateInput = {
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
  kunde: Prisma.KundeCreateNestedOneWithoutAusleihenInput
  exemplar: Prisma.ExemplarCreateNestedOneWithoutAusleihenInput
}

export type AusleihenUncheckedCreateInput = {
  kunde_id: number
  exemplar_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenUpdateInput = {
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kunde?: Prisma.KundeUpdateOneRequiredWithoutAusleihenNestedInput
  exemplar?: Prisma.ExemplarUpdateOneRequiredWithoutAusleihenNestedInput
}

export type AusleihenUncheckedUpdateInput = {
  kunde_id?: Prisma.IntFieldUpdateOperationsInput | number
  exemplar_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenCreateManyInput = {
  kunde_id: number
  exemplar_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenUpdateManyMutationInput = {
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenUncheckedUpdateManyInput = {
  kunde_id?: Prisma.IntFieldUpdateOperationsInput | number
  exemplar_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenListRelationFilter = {
  every?: Prisma.AusleihenWhereInput
  some?: Prisma.AusleihenWhereInput
  none?: Prisma.AusleihenWhereInput
}

export type AusleihenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AusleihenKunde_idExemplar_idCompoundUniqueInput = {
  kunde_id: number
  exemplar_id: number
}

export type AusleihenCountOrderByAggregateInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
  ausleihdatum?: Prisma.SortOrder
  rueckgabedatum?: Prisma.SortOrder
}

export type AusleihenAvgOrderByAggregateInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
}

export type AusleihenMaxOrderByAggregateInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
  ausleihdatum?: Prisma.SortOrder
  rueckgabedatum?: Prisma.SortOrder
}

export type AusleihenMinOrderByAggregateInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
  ausleihdatum?: Prisma.SortOrder
  rueckgabedatum?: Prisma.SortOrder
}

export type AusleihenSumOrderByAggregateInput = {
  kunde_id?: Prisma.SortOrder
  exemplar_id?: Prisma.SortOrder
}

export type AusleihenCreateNestedManyWithoutExemplarInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput> | Prisma.AusleihenCreateWithoutExemplarInput[] | Prisma.AusleihenUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutExemplarInput | Prisma.AusleihenCreateOrConnectWithoutExemplarInput[]
  createMany?: Prisma.AusleihenCreateManyExemplarInputEnvelope
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
}

export type AusleihenUncheckedCreateNestedManyWithoutExemplarInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput> | Prisma.AusleihenCreateWithoutExemplarInput[] | Prisma.AusleihenUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutExemplarInput | Prisma.AusleihenCreateOrConnectWithoutExemplarInput[]
  createMany?: Prisma.AusleihenCreateManyExemplarInputEnvelope
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
}

export type AusleihenUpdateManyWithoutExemplarNestedInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput> | Prisma.AusleihenCreateWithoutExemplarInput[] | Prisma.AusleihenUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutExemplarInput | Prisma.AusleihenCreateOrConnectWithoutExemplarInput[]
  upsert?: Prisma.AusleihenUpsertWithWhereUniqueWithoutExemplarInput | Prisma.AusleihenUpsertWithWhereUniqueWithoutExemplarInput[]
  createMany?: Prisma.AusleihenCreateManyExemplarInputEnvelope
  set?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  disconnect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  delete?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  update?: Prisma.AusleihenUpdateWithWhereUniqueWithoutExemplarInput | Prisma.AusleihenUpdateWithWhereUniqueWithoutExemplarInput[]
  updateMany?: Prisma.AusleihenUpdateManyWithWhereWithoutExemplarInput | Prisma.AusleihenUpdateManyWithWhereWithoutExemplarInput[]
  deleteMany?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
}

export type AusleihenUncheckedUpdateManyWithoutExemplarNestedInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput> | Prisma.AusleihenCreateWithoutExemplarInput[] | Prisma.AusleihenUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutExemplarInput | Prisma.AusleihenCreateOrConnectWithoutExemplarInput[]
  upsert?: Prisma.AusleihenUpsertWithWhereUniqueWithoutExemplarInput | Prisma.AusleihenUpsertWithWhereUniqueWithoutExemplarInput[]
  createMany?: Prisma.AusleihenCreateManyExemplarInputEnvelope
  set?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  disconnect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  delete?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  update?: Prisma.AusleihenUpdateWithWhereUniqueWithoutExemplarInput | Prisma.AusleihenUpdateWithWhereUniqueWithoutExemplarInput[]
  updateMany?: Prisma.AusleihenUpdateManyWithWhereWithoutExemplarInput | Prisma.AusleihenUpdateManyWithWhereWithoutExemplarInput[]
  deleteMany?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
}

export type AusleihenCreateNestedManyWithoutKundeInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput> | Prisma.AusleihenCreateWithoutKundeInput[] | Prisma.AusleihenUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutKundeInput | Prisma.AusleihenCreateOrConnectWithoutKundeInput[]
  createMany?: Prisma.AusleihenCreateManyKundeInputEnvelope
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
}

export type AusleihenUncheckedCreateNestedManyWithoutKundeInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput> | Prisma.AusleihenCreateWithoutKundeInput[] | Prisma.AusleihenUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutKundeInput | Prisma.AusleihenCreateOrConnectWithoutKundeInput[]
  createMany?: Prisma.AusleihenCreateManyKundeInputEnvelope
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
}

export type AusleihenUpdateManyWithoutKundeNestedInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput> | Prisma.AusleihenCreateWithoutKundeInput[] | Prisma.AusleihenUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutKundeInput | Prisma.AusleihenCreateOrConnectWithoutKundeInput[]
  upsert?: Prisma.AusleihenUpsertWithWhereUniqueWithoutKundeInput | Prisma.AusleihenUpsertWithWhereUniqueWithoutKundeInput[]
  createMany?: Prisma.AusleihenCreateManyKundeInputEnvelope
  set?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  disconnect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  delete?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  update?: Prisma.AusleihenUpdateWithWhereUniqueWithoutKundeInput | Prisma.AusleihenUpdateWithWhereUniqueWithoutKundeInput[]
  updateMany?: Prisma.AusleihenUpdateManyWithWhereWithoutKundeInput | Prisma.AusleihenUpdateManyWithWhereWithoutKundeInput[]
  deleteMany?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
}

export type AusleihenUncheckedUpdateManyWithoutKundeNestedInput = {
  create?: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput> | Prisma.AusleihenCreateWithoutKundeInput[] | Prisma.AusleihenUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.AusleihenCreateOrConnectWithoutKundeInput | Prisma.AusleihenCreateOrConnectWithoutKundeInput[]
  upsert?: Prisma.AusleihenUpsertWithWhereUniqueWithoutKundeInput | Prisma.AusleihenUpsertWithWhereUniqueWithoutKundeInput[]
  createMany?: Prisma.AusleihenCreateManyKundeInputEnvelope
  set?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  disconnect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  delete?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  connect?: Prisma.AusleihenWhereUniqueInput | Prisma.AusleihenWhereUniqueInput[]
  update?: Prisma.AusleihenUpdateWithWhereUniqueWithoutKundeInput | Prisma.AusleihenUpdateWithWhereUniqueWithoutKundeInput[]
  updateMany?: Prisma.AusleihenUpdateManyWithWhereWithoutKundeInput | Prisma.AusleihenUpdateManyWithWhereWithoutKundeInput[]
  deleteMany?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type AusleihenCreateWithoutExemplarInput = {
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
  kunde: Prisma.KundeCreateNestedOneWithoutAusleihenInput
}

export type AusleihenUncheckedCreateWithoutExemplarInput = {
  kunde_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenCreateOrConnectWithoutExemplarInput = {
  where: Prisma.AusleihenWhereUniqueInput
  create: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput>
}

export type AusleihenCreateManyExemplarInputEnvelope = {
  data: Prisma.AusleihenCreateManyExemplarInput | Prisma.AusleihenCreateManyExemplarInput[]
}

export type AusleihenUpsertWithWhereUniqueWithoutExemplarInput = {
  where: Prisma.AusleihenWhereUniqueInput
  update: Prisma.XOR<Prisma.AusleihenUpdateWithoutExemplarInput, Prisma.AusleihenUncheckedUpdateWithoutExemplarInput>
  create: Prisma.XOR<Prisma.AusleihenCreateWithoutExemplarInput, Prisma.AusleihenUncheckedCreateWithoutExemplarInput>
}

export type AusleihenUpdateWithWhereUniqueWithoutExemplarInput = {
  where: Prisma.AusleihenWhereUniqueInput
  data: Prisma.XOR<Prisma.AusleihenUpdateWithoutExemplarInput, Prisma.AusleihenUncheckedUpdateWithoutExemplarInput>
}

export type AusleihenUpdateManyWithWhereWithoutExemplarInput = {
  where: Prisma.AusleihenScalarWhereInput
  data: Prisma.XOR<Prisma.AusleihenUpdateManyMutationInput, Prisma.AusleihenUncheckedUpdateManyWithoutExemplarInput>
}

export type AusleihenScalarWhereInput = {
  AND?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
  OR?: Prisma.AusleihenScalarWhereInput[]
  NOT?: Prisma.AusleihenScalarWhereInput | Prisma.AusleihenScalarWhereInput[]
  kunde_id?: Prisma.IntFilter<"Ausleihen"> | number
  exemplar_id?: Prisma.IntFilter<"Ausleihen"> | number
  ausleihdatum?: Prisma.DateTimeFilter<"Ausleihen"> | Date | string
  rueckgabedatum?: Prisma.DateTimeNullableFilter<"Ausleihen"> | Date | string | null
}

export type AusleihenCreateWithoutKundeInput = {
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
  exemplar: Prisma.ExemplarCreateNestedOneWithoutAusleihenInput
}

export type AusleihenUncheckedCreateWithoutKundeInput = {
  exemplar_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenCreateOrConnectWithoutKundeInput = {
  where: Prisma.AusleihenWhereUniqueInput
  create: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput>
}

export type AusleihenCreateManyKundeInputEnvelope = {
  data: Prisma.AusleihenCreateManyKundeInput | Prisma.AusleihenCreateManyKundeInput[]
}

export type AusleihenUpsertWithWhereUniqueWithoutKundeInput = {
  where: Prisma.AusleihenWhereUniqueInput
  update: Prisma.XOR<Prisma.AusleihenUpdateWithoutKundeInput, Prisma.AusleihenUncheckedUpdateWithoutKundeInput>
  create: Prisma.XOR<Prisma.AusleihenCreateWithoutKundeInput, Prisma.AusleihenUncheckedCreateWithoutKundeInput>
}

export type AusleihenUpdateWithWhereUniqueWithoutKundeInput = {
  where: Prisma.AusleihenWhereUniqueInput
  data: Prisma.XOR<Prisma.AusleihenUpdateWithoutKundeInput, Prisma.AusleihenUncheckedUpdateWithoutKundeInput>
}

export type AusleihenUpdateManyWithWhereWithoutKundeInput = {
  where: Prisma.AusleihenScalarWhereInput
  data: Prisma.XOR<Prisma.AusleihenUpdateManyMutationInput, Prisma.AusleihenUncheckedUpdateManyWithoutKundeInput>
}

export type AusleihenCreateManyExemplarInput = {
  kunde_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenUpdateWithoutExemplarInput = {
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kunde?: Prisma.KundeUpdateOneRequiredWithoutAusleihenNestedInput
}

export type AusleihenUncheckedUpdateWithoutExemplarInput = {
  kunde_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenUncheckedUpdateManyWithoutExemplarInput = {
  kunde_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenCreateManyKundeInput = {
  exemplar_id: number
  ausleihdatum?: Date | string
  rueckgabedatum?: Date | string | null
}

export type AusleihenUpdateWithoutKundeInput = {
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  exemplar?: Prisma.ExemplarUpdateOneRequiredWithoutAusleihenNestedInput
}

export type AusleihenUncheckedUpdateWithoutKundeInput = {
  exemplar_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AusleihenUncheckedUpdateManyWithoutKundeInput = {
  exemplar_id?: Prisma.IntFieldUpdateOperationsInput | number
  ausleihdatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabedatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type AusleihenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  kunde_id?: boolean
  exemplar_id?: boolean
  ausleihdatum?: boolean
  rueckgabedatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ausleihen"]>

export type AusleihenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  kunde_id?: boolean
  exemplar_id?: boolean
  ausleihdatum?: boolean
  rueckgabedatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ausleihen"]>

export type AusleihenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  kunde_id?: boolean
  exemplar_id?: boolean
  ausleihdatum?: boolean
  rueckgabedatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ausleihen"]>

export type AusleihenSelectScalar = {
  kunde_id?: boolean
  exemplar_id?: boolean
  ausleihdatum?: boolean
  rueckgabedatum?: boolean
}

export type AusleihenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"kunde_id" | "exemplar_id" | "ausleihdatum" | "rueckgabedatum", ExtArgs["result"]["ausleihen"]>
export type AusleihenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}
export type AusleihenIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}
export type AusleihenIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
}

export type $AusleihenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ausleihen"
  objects: {
    kunde: Prisma.$KundePayload<ExtArgs>
    exemplar: Prisma.$ExemplarPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    kunde_id: number
    exemplar_id: number
    ausleihdatum: Date
    rueckgabedatum: Date | null
  }, ExtArgs["result"]["ausleihen"]>
  composites: {}
}

export type AusleihenGetPayload<S extends boolean | null | undefined | AusleihenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AusleihenPayload, S>

export type AusleihenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AusleihenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AusleihenCountAggregateInputType | true
  }

export interface AusleihenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ausleihen'], meta: { name: 'Ausleihen' } }
  /**
   * Find zero or one Ausleihen that matches the filter.
   * @param {AusleihenFindUniqueArgs} args - Arguments to find a Ausleihen
   * @example
   * // Get one Ausleihen
   * const ausleihen = await prisma.ausleihen.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AusleihenFindUniqueArgs>(args: Prisma.SelectSubset<T, AusleihenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ausleihen that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AusleihenFindUniqueOrThrowArgs} args - Arguments to find a Ausleihen
   * @example
   * // Get one Ausleihen
   * const ausleihen = await prisma.ausleihen.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AusleihenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AusleihenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ausleihen that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenFindFirstArgs} args - Arguments to find a Ausleihen
   * @example
   * // Get one Ausleihen
   * const ausleihen = await prisma.ausleihen.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AusleihenFindFirstArgs>(args?: Prisma.SelectSubset<T, AusleihenFindFirstArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ausleihen that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenFindFirstOrThrowArgs} args - Arguments to find a Ausleihen
   * @example
   * // Get one Ausleihen
   * const ausleihen = await prisma.ausleihen.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AusleihenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AusleihenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Ausleihens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Ausleihens
   * const ausleihens = await prisma.ausleihen.findMany()
   * 
   * // Get first 10 Ausleihens
   * const ausleihens = await prisma.ausleihen.findMany({ take: 10 })
   * 
   * // Only select the `kunde_id`
   * const ausleihenWithKunde_idOnly = await prisma.ausleihen.findMany({ select: { kunde_id: true } })
   * 
   */
  findMany<T extends AusleihenFindManyArgs>(args?: Prisma.SelectSubset<T, AusleihenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ausleihen.
   * @param {AusleihenCreateArgs} args - Arguments to create a Ausleihen.
   * @example
   * // Create one Ausleihen
   * const Ausleihen = await prisma.ausleihen.create({
   *   data: {
   *     // ... data to create a Ausleihen
   *   }
   * })
   * 
   */
  create<T extends AusleihenCreateArgs>(args: Prisma.SelectSubset<T, AusleihenCreateArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Ausleihens.
   * @param {AusleihenCreateManyArgs} args - Arguments to create many Ausleihens.
   * @example
   * // Create many Ausleihens
   * const ausleihen = await prisma.ausleihen.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AusleihenCreateManyArgs>(args?: Prisma.SelectSubset<T, AusleihenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Ausleihens and returns the data saved in the database.
   * @param {AusleihenCreateManyAndReturnArgs} args - Arguments to create many Ausleihens.
   * @example
   * // Create many Ausleihens
   * const ausleihen = await prisma.ausleihen.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Ausleihens and only return the `kunde_id`
   * const ausleihenWithKunde_idOnly = await prisma.ausleihen.createManyAndReturn({
   *   select: { kunde_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AusleihenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AusleihenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ausleihen.
   * @param {AusleihenDeleteArgs} args - Arguments to delete one Ausleihen.
   * @example
   * // Delete one Ausleihen
   * const Ausleihen = await prisma.ausleihen.delete({
   *   where: {
   *     // ... filter to delete one Ausleihen
   *   }
   * })
   * 
   */
  delete<T extends AusleihenDeleteArgs>(args: Prisma.SelectSubset<T, AusleihenDeleteArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ausleihen.
   * @param {AusleihenUpdateArgs} args - Arguments to update one Ausleihen.
   * @example
   * // Update one Ausleihen
   * const ausleihen = await prisma.ausleihen.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AusleihenUpdateArgs>(args: Prisma.SelectSubset<T, AusleihenUpdateArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Ausleihens.
   * @param {AusleihenDeleteManyArgs} args - Arguments to filter Ausleihens to delete.
   * @example
   * // Delete a few Ausleihens
   * const { count } = await prisma.ausleihen.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AusleihenDeleteManyArgs>(args?: Prisma.SelectSubset<T, AusleihenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ausleihens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Ausleihens
   * const ausleihen = await prisma.ausleihen.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AusleihenUpdateManyArgs>(args: Prisma.SelectSubset<T, AusleihenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ausleihens and returns the data updated in the database.
   * @param {AusleihenUpdateManyAndReturnArgs} args - Arguments to update many Ausleihens.
   * @example
   * // Update many Ausleihens
   * const ausleihen = await prisma.ausleihen.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Ausleihens and only return the `kunde_id`
   * const ausleihenWithKunde_idOnly = await prisma.ausleihen.updateManyAndReturn({
   *   select: { kunde_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AusleihenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AusleihenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ausleihen.
   * @param {AusleihenUpsertArgs} args - Arguments to update or create a Ausleihen.
   * @example
   * // Update or create a Ausleihen
   * const ausleihen = await prisma.ausleihen.upsert({
   *   create: {
   *     // ... data to create a Ausleihen
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ausleihen we want to update
   *   }
   * })
   */
  upsert<T extends AusleihenUpsertArgs>(args: Prisma.SelectSubset<T, AusleihenUpsertArgs<ExtArgs>>): Prisma.Prisma__AusleihenClient<runtime.Types.Result.GetResult<Prisma.$AusleihenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Ausleihens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenCountArgs} args - Arguments to filter Ausleihens to count.
   * @example
   * // Count the number of Ausleihens
   * const count = await prisma.ausleihen.count({
   *   where: {
   *     // ... the filter for the Ausleihens we want to count
   *   }
   * })
  **/
  count<T extends AusleihenCountArgs>(
    args?: Prisma.Subset<T, AusleihenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AusleihenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ausleihen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AusleihenAggregateArgs>(args: Prisma.Subset<T, AusleihenAggregateArgs>): Prisma.PrismaPromise<GetAusleihenAggregateType<T>>

  /**
   * Group by Ausleihen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AusleihenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AusleihenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AusleihenGroupByArgs['orderBy'] }
      : { orderBy?: AusleihenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AusleihenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAusleihenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ausleihen model
 */
readonly fields: AusleihenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ausleihen.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AusleihenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kunde<T extends Prisma.KundeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KundeDefaultArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  exemplar<T extends Prisma.ExemplarDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExemplarDefaultArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ausleihen model
 */
export interface AusleihenFieldRefs {
  readonly kunde_id: Prisma.FieldRef<"Ausleihen", 'Int'>
  readonly exemplar_id: Prisma.FieldRef<"Ausleihen", 'Int'>
  readonly ausleihdatum: Prisma.FieldRef<"Ausleihen", 'DateTime'>
  readonly rueckgabedatum: Prisma.FieldRef<"Ausleihen", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Ausleihen findUnique
 */
export type AusleihenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter, which Ausleihen to fetch.
   */
  where: Prisma.AusleihenWhereUniqueInput
}

/**
 * Ausleihen findUniqueOrThrow
 */
export type AusleihenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter, which Ausleihen to fetch.
   */
  where: Prisma.AusleihenWhereUniqueInput
}

/**
 * Ausleihen findFirst
 */
export type AusleihenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter, which Ausleihen to fetch.
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ausleihens to fetch.
   */
  orderBy?: Prisma.AusleihenOrderByWithRelationInput | Prisma.AusleihenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ausleihens.
   */
  cursor?: Prisma.AusleihenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ausleihens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ausleihens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ausleihens.
   */
  distinct?: Prisma.AusleihenScalarFieldEnum | Prisma.AusleihenScalarFieldEnum[]
}

/**
 * Ausleihen findFirstOrThrow
 */
export type AusleihenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter, which Ausleihen to fetch.
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ausleihens to fetch.
   */
  orderBy?: Prisma.AusleihenOrderByWithRelationInput | Prisma.AusleihenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ausleihens.
   */
  cursor?: Prisma.AusleihenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ausleihens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ausleihens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ausleihens.
   */
  distinct?: Prisma.AusleihenScalarFieldEnum | Prisma.AusleihenScalarFieldEnum[]
}

/**
 * Ausleihen findMany
 */
export type AusleihenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter, which Ausleihens to fetch.
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ausleihens to fetch.
   */
  orderBy?: Prisma.AusleihenOrderByWithRelationInput | Prisma.AusleihenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Ausleihens.
   */
  cursor?: Prisma.AusleihenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ausleihens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ausleihens.
   */
  skip?: number
  distinct?: Prisma.AusleihenScalarFieldEnum | Prisma.AusleihenScalarFieldEnum[]
}

/**
 * Ausleihen create
 */
export type AusleihenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * The data needed to create a Ausleihen.
   */
  data: Prisma.XOR<Prisma.AusleihenCreateInput, Prisma.AusleihenUncheckedCreateInput>
}

/**
 * Ausleihen createMany
 */
export type AusleihenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Ausleihens.
   */
  data: Prisma.AusleihenCreateManyInput | Prisma.AusleihenCreateManyInput[]
}

/**
 * Ausleihen createManyAndReturn
 */
export type AusleihenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * The data used to create many Ausleihens.
   */
  data: Prisma.AusleihenCreateManyInput | Prisma.AusleihenCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Ausleihen update
 */
export type AusleihenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * The data needed to update a Ausleihen.
   */
  data: Prisma.XOR<Prisma.AusleihenUpdateInput, Prisma.AusleihenUncheckedUpdateInput>
  /**
   * Choose, which Ausleihen to update.
   */
  where: Prisma.AusleihenWhereUniqueInput
}

/**
 * Ausleihen updateMany
 */
export type AusleihenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Ausleihens.
   */
  data: Prisma.XOR<Prisma.AusleihenUpdateManyMutationInput, Prisma.AusleihenUncheckedUpdateManyInput>
  /**
   * Filter which Ausleihens to update
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * Limit how many Ausleihens to update.
   */
  limit?: number
}

/**
 * Ausleihen updateManyAndReturn
 */
export type AusleihenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * The data used to update Ausleihens.
   */
  data: Prisma.XOR<Prisma.AusleihenUpdateManyMutationInput, Prisma.AusleihenUncheckedUpdateManyInput>
  /**
   * Filter which Ausleihens to update
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * Limit how many Ausleihens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Ausleihen upsert
 */
export type AusleihenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * The filter to search for the Ausleihen to update in case it exists.
   */
  where: Prisma.AusleihenWhereUniqueInput
  /**
   * In case the Ausleihen found by the `where` argument doesn't exist, create a new Ausleihen with this data.
   */
  create: Prisma.XOR<Prisma.AusleihenCreateInput, Prisma.AusleihenUncheckedCreateInput>
  /**
   * In case the Ausleihen was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AusleihenUpdateInput, Prisma.AusleihenUncheckedUpdateInput>
}

/**
 * Ausleihen delete
 */
export type AusleihenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
  /**
   * Filter which Ausleihen to delete.
   */
  where: Prisma.AusleihenWhereUniqueInput
}

/**
 * Ausleihen deleteMany
 */
export type AusleihenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ausleihens to delete
   */
  where?: Prisma.AusleihenWhereInput
  /**
   * Limit how many Ausleihens to delete.
   */
  limit?: number
}

/**
 * Ausleihen without action
 */
export type AusleihenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ausleihen
   */
  select?: Prisma.AusleihenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ausleihen
   */
  omit?: Prisma.AusleihenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AusleihenInclude<ExtArgs> | null
}
