
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Mitarbeiter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Mitarbeiter
 * 
 */
export type MitarbeiterModel = runtime.Types.Result.DefaultSelection<Prisma.$MitarbeiterPayload>

export type AggregateMitarbeiter = {
  _count: MitarbeiterCountAggregateOutputType | null
  _avg: MitarbeiterAvgAggregateOutputType | null
  _sum: MitarbeiterSumAggregateOutputType | null
  _min: MitarbeiterMinAggregateOutputType | null
  _max: MitarbeiterMaxAggregateOutputType | null
}

export type MitarbeiterAvgAggregateOutputType = {
  mitarbeiter_id: number | null
  filiale_id: number | null
}

export type MitarbeiterSumAggregateOutputType = {
  mitarbeiter_id: number | null
  filiale_id: number | null
}

export type MitarbeiterMinAggregateOutputType = {
  mitarbeiter_id: number | null
  name: string | null
  filiale_id: number | null
}

export type MitarbeiterMaxAggregateOutputType = {
  mitarbeiter_id: number | null
  name: string | null
  filiale_id: number | null
}

export type MitarbeiterCountAggregateOutputType = {
  mitarbeiter_id: number
  name: number
  filiale_id: number
  _all: number
}


export type MitarbeiterAvgAggregateInputType = {
  mitarbeiter_id?: true
  filiale_id?: true
}

export type MitarbeiterSumAggregateInputType = {
  mitarbeiter_id?: true
  filiale_id?: true
}

export type MitarbeiterMinAggregateInputType = {
  mitarbeiter_id?: true
  name?: true
  filiale_id?: true
}

export type MitarbeiterMaxAggregateInputType = {
  mitarbeiter_id?: true
  name?: true
  filiale_id?: true
}

export type MitarbeiterCountAggregateInputType = {
  mitarbeiter_id?: true
  name?: true
  filiale_id?: true
  _all?: true
}

export type MitarbeiterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mitarbeiter to aggregate.
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mitarbeiters to fetch.
   */
  orderBy?: Prisma.MitarbeiterOrderByWithRelationInput | Prisma.MitarbeiterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MitarbeiterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mitarbeiters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mitarbeiters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mitarbeiters
  **/
  _count?: true | MitarbeiterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MitarbeiterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MitarbeiterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MitarbeiterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MitarbeiterMaxAggregateInputType
}

export type GetMitarbeiterAggregateType<T extends MitarbeiterAggregateArgs> = {
      [P in keyof T & keyof AggregateMitarbeiter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMitarbeiter[P]>
    : Prisma.GetScalarType<T[P], AggregateMitarbeiter[P]>
}




export type MitarbeiterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MitarbeiterWhereInput
  orderBy?: Prisma.MitarbeiterOrderByWithAggregationInput | Prisma.MitarbeiterOrderByWithAggregationInput[]
  by: Prisma.MitarbeiterScalarFieldEnum[] | Prisma.MitarbeiterScalarFieldEnum
  having?: Prisma.MitarbeiterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MitarbeiterCountAggregateInputType | true
  _avg?: MitarbeiterAvgAggregateInputType
  _sum?: MitarbeiterSumAggregateInputType
  _min?: MitarbeiterMinAggregateInputType
  _max?: MitarbeiterMaxAggregateInputType
}

export type MitarbeiterGroupByOutputType = {
  mitarbeiter_id: number
  name: string
  filiale_id: number
  _count: MitarbeiterCountAggregateOutputType | null
  _avg: MitarbeiterAvgAggregateOutputType | null
  _sum: MitarbeiterSumAggregateOutputType | null
  _min: MitarbeiterMinAggregateOutputType | null
  _max: MitarbeiterMaxAggregateOutputType | null
}

type GetMitarbeiterGroupByPayload<T extends MitarbeiterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MitarbeiterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MitarbeiterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MitarbeiterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MitarbeiterGroupByOutputType[P]>
      }
    >
  >



export type MitarbeiterWhereInput = {
  AND?: Prisma.MitarbeiterWhereInput | Prisma.MitarbeiterWhereInput[]
  OR?: Prisma.MitarbeiterWhereInput[]
  NOT?: Prisma.MitarbeiterWhereInput | Prisma.MitarbeiterWhereInput[]
  mitarbeiter_id?: Prisma.IntFilter<"Mitarbeiter"> | number
  name?: Prisma.StringFilter<"Mitarbeiter"> | string
  filiale_id?: Prisma.IntFilter<"Mitarbeiter"> | number
  filiale?: Prisma.XOR<Prisma.FilialeScalarRelationFilter, Prisma.FilialeWhereInput>
}

export type MitarbeiterOrderByWithRelationInput = {
  mitarbeiter_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
  filiale?: Prisma.FilialeOrderByWithRelationInput
}

export type MitarbeiterWhereUniqueInput = Prisma.AtLeast<{
  mitarbeiter_id?: number
  AND?: Prisma.MitarbeiterWhereInput | Prisma.MitarbeiterWhereInput[]
  OR?: Prisma.MitarbeiterWhereInput[]
  NOT?: Prisma.MitarbeiterWhereInput | Prisma.MitarbeiterWhereInput[]
  name?: Prisma.StringFilter<"Mitarbeiter"> | string
  filiale_id?: Prisma.IntFilter<"Mitarbeiter"> | number
  filiale?: Prisma.XOR<Prisma.FilialeScalarRelationFilter, Prisma.FilialeWhereInput>
}, "mitarbeiter_id">

export type MitarbeiterOrderByWithAggregationInput = {
  mitarbeiter_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
  _count?: Prisma.MitarbeiterCountOrderByAggregateInput
  _avg?: Prisma.MitarbeiterAvgOrderByAggregateInput
  _max?: Prisma.MitarbeiterMaxOrderByAggregateInput
  _min?: Prisma.MitarbeiterMinOrderByAggregateInput
  _sum?: Prisma.MitarbeiterSumOrderByAggregateInput
}

export type MitarbeiterScalarWhereWithAggregatesInput = {
  AND?: Prisma.MitarbeiterScalarWhereWithAggregatesInput | Prisma.MitarbeiterScalarWhereWithAggregatesInput[]
  OR?: Prisma.MitarbeiterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MitarbeiterScalarWhereWithAggregatesInput | Prisma.MitarbeiterScalarWhereWithAggregatesInput[]
  mitarbeiter_id?: Prisma.IntWithAggregatesFilter<"Mitarbeiter"> | number
  name?: Prisma.StringWithAggregatesFilter<"Mitarbeiter"> | string
  filiale_id?: Prisma.IntWithAggregatesFilter<"Mitarbeiter"> | number
}

export type MitarbeiterCreateInput = {
  name: string
  filiale: Prisma.FilialeCreateNestedOneWithoutMitarbeiterInput
}

export type MitarbeiterUncheckedCreateInput = {
  mitarbeiter_id?: number
  name: string
  filiale_id: number
}

export type MitarbeiterUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  filiale?: Prisma.FilialeUpdateOneRequiredWithoutMitarbeiterNestedInput
}

export type MitarbeiterUncheckedUpdateInput = {
  mitarbeiter_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  filiale_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MitarbeiterCreateManyInput = {
  mitarbeiter_id?: number
  name: string
  filiale_id: number
}

export type MitarbeiterUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MitarbeiterUncheckedUpdateManyInput = {
  mitarbeiter_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  filiale_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MitarbeiterListRelationFilter = {
  every?: Prisma.MitarbeiterWhereInput
  some?: Prisma.MitarbeiterWhereInput
  none?: Prisma.MitarbeiterWhereInput
}

export type MitarbeiterOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MitarbeiterCountOrderByAggregateInput = {
  mitarbeiter_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
}

export type MitarbeiterAvgOrderByAggregateInput = {
  mitarbeiter_id?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
}

export type MitarbeiterMaxOrderByAggregateInput = {
  mitarbeiter_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
}

export type MitarbeiterMinOrderByAggregateInput = {
  mitarbeiter_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
}

export type MitarbeiterSumOrderByAggregateInput = {
  mitarbeiter_id?: Prisma.SortOrder
  filiale_id?: Prisma.SortOrder
}

export type MitarbeiterCreateNestedManyWithoutFilialeInput = {
  create?: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput> | Prisma.MitarbeiterCreateWithoutFilialeInput[] | Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput | Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput[]
  createMany?: Prisma.MitarbeiterCreateManyFilialeInputEnvelope
  connect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
}

export type MitarbeiterUncheckedCreateNestedManyWithoutFilialeInput = {
  create?: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput> | Prisma.MitarbeiterCreateWithoutFilialeInput[] | Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput | Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput[]
  createMany?: Prisma.MitarbeiterCreateManyFilialeInputEnvelope
  connect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
}

export type MitarbeiterUpdateManyWithoutFilialeNestedInput = {
  create?: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput> | Prisma.MitarbeiterCreateWithoutFilialeInput[] | Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput | Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput[]
  upsert?: Prisma.MitarbeiterUpsertWithWhereUniqueWithoutFilialeInput | Prisma.MitarbeiterUpsertWithWhereUniqueWithoutFilialeInput[]
  createMany?: Prisma.MitarbeiterCreateManyFilialeInputEnvelope
  set?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  disconnect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  delete?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  connect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  update?: Prisma.MitarbeiterUpdateWithWhereUniqueWithoutFilialeInput | Prisma.MitarbeiterUpdateWithWhereUniqueWithoutFilialeInput[]
  updateMany?: Prisma.MitarbeiterUpdateManyWithWhereWithoutFilialeInput | Prisma.MitarbeiterUpdateManyWithWhereWithoutFilialeInput[]
  deleteMany?: Prisma.MitarbeiterScalarWhereInput | Prisma.MitarbeiterScalarWhereInput[]
}

export type MitarbeiterUncheckedUpdateManyWithoutFilialeNestedInput = {
  create?: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput> | Prisma.MitarbeiterCreateWithoutFilialeInput[] | Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput | Prisma.MitarbeiterCreateOrConnectWithoutFilialeInput[]
  upsert?: Prisma.MitarbeiterUpsertWithWhereUniqueWithoutFilialeInput | Prisma.MitarbeiterUpsertWithWhereUniqueWithoutFilialeInput[]
  createMany?: Prisma.MitarbeiterCreateManyFilialeInputEnvelope
  set?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  disconnect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  delete?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  connect?: Prisma.MitarbeiterWhereUniqueInput | Prisma.MitarbeiterWhereUniqueInput[]
  update?: Prisma.MitarbeiterUpdateWithWhereUniqueWithoutFilialeInput | Prisma.MitarbeiterUpdateWithWhereUniqueWithoutFilialeInput[]
  updateMany?: Prisma.MitarbeiterUpdateManyWithWhereWithoutFilialeInput | Prisma.MitarbeiterUpdateManyWithWhereWithoutFilialeInput[]
  deleteMany?: Prisma.MitarbeiterScalarWhereInput | Prisma.MitarbeiterScalarWhereInput[]
}

export type MitarbeiterCreateWithoutFilialeInput = {
  name: string
}

export type MitarbeiterUncheckedCreateWithoutFilialeInput = {
  mitarbeiter_id?: number
  name: string
}

export type MitarbeiterCreateOrConnectWithoutFilialeInput = {
  where: Prisma.MitarbeiterWhereUniqueInput
  create: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput>
}

export type MitarbeiterCreateManyFilialeInputEnvelope = {
  data: Prisma.MitarbeiterCreateManyFilialeInput | Prisma.MitarbeiterCreateManyFilialeInput[]
}

export type MitarbeiterUpsertWithWhereUniqueWithoutFilialeInput = {
  where: Prisma.MitarbeiterWhereUniqueInput
  update: Prisma.XOR<Prisma.MitarbeiterUpdateWithoutFilialeInput, Prisma.MitarbeiterUncheckedUpdateWithoutFilialeInput>
  create: Prisma.XOR<Prisma.MitarbeiterCreateWithoutFilialeInput, Prisma.MitarbeiterUncheckedCreateWithoutFilialeInput>
}

export type MitarbeiterUpdateWithWhereUniqueWithoutFilialeInput = {
  where: Prisma.MitarbeiterWhereUniqueInput
  data: Prisma.XOR<Prisma.MitarbeiterUpdateWithoutFilialeInput, Prisma.MitarbeiterUncheckedUpdateWithoutFilialeInput>
}

export type MitarbeiterUpdateManyWithWhereWithoutFilialeInput = {
  where: Prisma.MitarbeiterScalarWhereInput
  data: Prisma.XOR<Prisma.MitarbeiterUpdateManyMutationInput, Prisma.MitarbeiterUncheckedUpdateManyWithoutFilialeInput>
}

export type MitarbeiterScalarWhereInput = {
  AND?: Prisma.MitarbeiterScalarWhereInput | Prisma.MitarbeiterScalarWhereInput[]
  OR?: Prisma.MitarbeiterScalarWhereInput[]
  NOT?: Prisma.MitarbeiterScalarWhereInput | Prisma.MitarbeiterScalarWhereInput[]
  mitarbeiter_id?: Prisma.IntFilter<"Mitarbeiter"> | number
  name?: Prisma.StringFilter<"Mitarbeiter"> | string
  filiale_id?: Prisma.IntFilter<"Mitarbeiter"> | number
}

export type MitarbeiterCreateManyFilialeInput = {
  mitarbeiter_id?: number
  name: string
}

export type MitarbeiterUpdateWithoutFilialeInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MitarbeiterUncheckedUpdateWithoutFilialeInput = {
  mitarbeiter_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MitarbeiterUncheckedUpdateManyWithoutFilialeInput = {
  mitarbeiter_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}



export type MitarbeiterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mitarbeiter_id?: boolean
  name?: boolean
  filiale_id?: boolean
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mitarbeiter"]>

export type MitarbeiterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mitarbeiter_id?: boolean
  name?: boolean
  filiale_id?: boolean
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mitarbeiter"]>

export type MitarbeiterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mitarbeiter_id?: boolean
  name?: boolean
  filiale_id?: boolean
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mitarbeiter"]>

export type MitarbeiterSelectScalar = {
  mitarbeiter_id?: boolean
  name?: boolean
  filiale_id?: boolean
}

export type MitarbeiterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"mitarbeiter_id" | "name" | "filiale_id", ExtArgs["result"]["mitarbeiter"]>
export type MitarbeiterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}
export type MitarbeiterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}
export type MitarbeiterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}

export type $MitarbeiterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mitarbeiter"
  objects: {
    filiale: Prisma.$FilialePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    mitarbeiter_id: number
    name: string
    filiale_id: number
  }, ExtArgs["result"]["mitarbeiter"]>
  composites: {}
}

export type MitarbeiterGetPayload<S extends boolean | null | undefined | MitarbeiterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload, S>

export type MitarbeiterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MitarbeiterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MitarbeiterCountAggregateInputType | true
  }

export interface MitarbeiterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mitarbeiter'], meta: { name: 'Mitarbeiter' } }
  /**
   * Find zero or one Mitarbeiter that matches the filter.
   * @param {MitarbeiterFindUniqueArgs} args - Arguments to find a Mitarbeiter
   * @example
   * // Get one Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MitarbeiterFindUniqueArgs>(args: Prisma.SelectSubset<T, MitarbeiterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mitarbeiter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MitarbeiterFindUniqueOrThrowArgs} args - Arguments to find a Mitarbeiter
   * @example
   * // Get one Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MitarbeiterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MitarbeiterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mitarbeiter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterFindFirstArgs} args - Arguments to find a Mitarbeiter
   * @example
   * // Get one Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MitarbeiterFindFirstArgs>(args?: Prisma.SelectSubset<T, MitarbeiterFindFirstArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mitarbeiter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterFindFirstOrThrowArgs} args - Arguments to find a Mitarbeiter
   * @example
   * // Get one Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MitarbeiterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MitarbeiterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mitarbeiters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mitarbeiters
   * const mitarbeiters = await prisma.mitarbeiter.findMany()
   * 
   * // Get first 10 Mitarbeiters
   * const mitarbeiters = await prisma.mitarbeiter.findMany({ take: 10 })
   * 
   * // Only select the `mitarbeiter_id`
   * const mitarbeiterWithMitarbeiter_idOnly = await prisma.mitarbeiter.findMany({ select: { mitarbeiter_id: true } })
   * 
   */
  findMany<T extends MitarbeiterFindManyArgs>(args?: Prisma.SelectSubset<T, MitarbeiterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mitarbeiter.
   * @param {MitarbeiterCreateArgs} args - Arguments to create a Mitarbeiter.
   * @example
   * // Create one Mitarbeiter
   * const Mitarbeiter = await prisma.mitarbeiter.create({
   *   data: {
   *     // ... data to create a Mitarbeiter
   *   }
   * })
   * 
   */
  create<T extends MitarbeiterCreateArgs>(args: Prisma.SelectSubset<T, MitarbeiterCreateArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mitarbeiters.
   * @param {MitarbeiterCreateManyArgs} args - Arguments to create many Mitarbeiters.
   * @example
   * // Create many Mitarbeiters
   * const mitarbeiter = await prisma.mitarbeiter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MitarbeiterCreateManyArgs>(args?: Prisma.SelectSubset<T, MitarbeiterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mitarbeiters and returns the data saved in the database.
   * @param {MitarbeiterCreateManyAndReturnArgs} args - Arguments to create many Mitarbeiters.
   * @example
   * // Create many Mitarbeiters
   * const mitarbeiter = await prisma.mitarbeiter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mitarbeiters and only return the `mitarbeiter_id`
   * const mitarbeiterWithMitarbeiter_idOnly = await prisma.mitarbeiter.createManyAndReturn({
   *   select: { mitarbeiter_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MitarbeiterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MitarbeiterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mitarbeiter.
   * @param {MitarbeiterDeleteArgs} args - Arguments to delete one Mitarbeiter.
   * @example
   * // Delete one Mitarbeiter
   * const Mitarbeiter = await prisma.mitarbeiter.delete({
   *   where: {
   *     // ... filter to delete one Mitarbeiter
   *   }
   * })
   * 
   */
  delete<T extends MitarbeiterDeleteArgs>(args: Prisma.SelectSubset<T, MitarbeiterDeleteArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mitarbeiter.
   * @param {MitarbeiterUpdateArgs} args - Arguments to update one Mitarbeiter.
   * @example
   * // Update one Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MitarbeiterUpdateArgs>(args: Prisma.SelectSubset<T, MitarbeiterUpdateArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mitarbeiters.
   * @param {MitarbeiterDeleteManyArgs} args - Arguments to filter Mitarbeiters to delete.
   * @example
   * // Delete a few Mitarbeiters
   * const { count } = await prisma.mitarbeiter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MitarbeiterDeleteManyArgs>(args?: Prisma.SelectSubset<T, MitarbeiterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mitarbeiters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mitarbeiters
   * const mitarbeiter = await prisma.mitarbeiter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MitarbeiterUpdateManyArgs>(args: Prisma.SelectSubset<T, MitarbeiterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mitarbeiters and returns the data updated in the database.
   * @param {MitarbeiterUpdateManyAndReturnArgs} args - Arguments to update many Mitarbeiters.
   * @example
   * // Update many Mitarbeiters
   * const mitarbeiter = await prisma.mitarbeiter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mitarbeiters and only return the `mitarbeiter_id`
   * const mitarbeiterWithMitarbeiter_idOnly = await prisma.mitarbeiter.updateManyAndReturn({
   *   select: { mitarbeiter_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MitarbeiterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MitarbeiterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mitarbeiter.
   * @param {MitarbeiterUpsertArgs} args - Arguments to update or create a Mitarbeiter.
   * @example
   * // Update or create a Mitarbeiter
   * const mitarbeiter = await prisma.mitarbeiter.upsert({
   *   create: {
   *     // ... data to create a Mitarbeiter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mitarbeiter we want to update
   *   }
   * })
   */
  upsert<T extends MitarbeiterUpsertArgs>(args: Prisma.SelectSubset<T, MitarbeiterUpsertArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mitarbeiters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterCountArgs} args - Arguments to filter Mitarbeiters to count.
   * @example
   * // Count the number of Mitarbeiters
   * const count = await prisma.mitarbeiter.count({
   *   where: {
   *     // ... the filter for the Mitarbeiters we want to count
   *   }
   * })
  **/
  count<T extends MitarbeiterCountArgs>(
    args?: Prisma.Subset<T, MitarbeiterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MitarbeiterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mitarbeiter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MitarbeiterAggregateArgs>(args: Prisma.Subset<T, MitarbeiterAggregateArgs>): Prisma.PrismaPromise<GetMitarbeiterAggregateType<T>>

  /**
   * Group by Mitarbeiter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MitarbeiterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MitarbeiterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MitarbeiterGroupByArgs['orderBy'] }
      : { orderBy?: MitarbeiterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MitarbeiterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMitarbeiterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mitarbeiter model
 */
readonly fields: MitarbeiterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mitarbeiter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MitarbeiterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  filiale<T extends Prisma.FilialeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilialeDefaultArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mitarbeiter model
 */
export interface MitarbeiterFieldRefs {
  readonly mitarbeiter_id: Prisma.FieldRef<"Mitarbeiter", 'Int'>
  readonly name: Prisma.FieldRef<"Mitarbeiter", 'String'>
  readonly filiale_id: Prisma.FieldRef<"Mitarbeiter", 'Int'>
}
    

// Custom InputTypes
/**
 * Mitarbeiter findUnique
 */
export type MitarbeiterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter, which Mitarbeiter to fetch.
   */
  where: Prisma.MitarbeiterWhereUniqueInput
}

/**
 * Mitarbeiter findUniqueOrThrow
 */
export type MitarbeiterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter, which Mitarbeiter to fetch.
   */
  where: Prisma.MitarbeiterWhereUniqueInput
}

/**
 * Mitarbeiter findFirst
 */
export type MitarbeiterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter, which Mitarbeiter to fetch.
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mitarbeiters to fetch.
   */
  orderBy?: Prisma.MitarbeiterOrderByWithRelationInput | Prisma.MitarbeiterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mitarbeiters.
   */
  cursor?: Prisma.MitarbeiterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mitarbeiters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mitarbeiters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mitarbeiters.
   */
  distinct?: Prisma.MitarbeiterScalarFieldEnum | Prisma.MitarbeiterScalarFieldEnum[]
}

/**
 * Mitarbeiter findFirstOrThrow
 */
export type MitarbeiterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter, which Mitarbeiter to fetch.
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mitarbeiters to fetch.
   */
  orderBy?: Prisma.MitarbeiterOrderByWithRelationInput | Prisma.MitarbeiterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mitarbeiters.
   */
  cursor?: Prisma.MitarbeiterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mitarbeiters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mitarbeiters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mitarbeiters.
   */
  distinct?: Prisma.MitarbeiterScalarFieldEnum | Prisma.MitarbeiterScalarFieldEnum[]
}

/**
 * Mitarbeiter findMany
 */
export type MitarbeiterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter, which Mitarbeiters to fetch.
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mitarbeiters to fetch.
   */
  orderBy?: Prisma.MitarbeiterOrderByWithRelationInput | Prisma.MitarbeiterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mitarbeiters.
   */
  cursor?: Prisma.MitarbeiterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mitarbeiters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mitarbeiters.
   */
  skip?: number
  distinct?: Prisma.MitarbeiterScalarFieldEnum | Prisma.MitarbeiterScalarFieldEnum[]
}

/**
 * Mitarbeiter create
 */
export type MitarbeiterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * The data needed to create a Mitarbeiter.
   */
  data: Prisma.XOR<Prisma.MitarbeiterCreateInput, Prisma.MitarbeiterUncheckedCreateInput>
}

/**
 * Mitarbeiter createMany
 */
export type MitarbeiterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mitarbeiters.
   */
  data: Prisma.MitarbeiterCreateManyInput | Prisma.MitarbeiterCreateManyInput[]
}

/**
 * Mitarbeiter createManyAndReturn
 */
export type MitarbeiterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * The data used to create many Mitarbeiters.
   */
  data: Prisma.MitarbeiterCreateManyInput | Prisma.MitarbeiterCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Mitarbeiter update
 */
export type MitarbeiterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * The data needed to update a Mitarbeiter.
   */
  data: Prisma.XOR<Prisma.MitarbeiterUpdateInput, Prisma.MitarbeiterUncheckedUpdateInput>
  /**
   * Choose, which Mitarbeiter to update.
   */
  where: Prisma.MitarbeiterWhereUniqueInput
}

/**
 * Mitarbeiter updateMany
 */
export type MitarbeiterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mitarbeiters.
   */
  data: Prisma.XOR<Prisma.MitarbeiterUpdateManyMutationInput, Prisma.MitarbeiterUncheckedUpdateManyInput>
  /**
   * Filter which Mitarbeiters to update
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * Limit how many Mitarbeiters to update.
   */
  limit?: number
}

/**
 * Mitarbeiter updateManyAndReturn
 */
export type MitarbeiterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * The data used to update Mitarbeiters.
   */
  data: Prisma.XOR<Prisma.MitarbeiterUpdateManyMutationInput, Prisma.MitarbeiterUncheckedUpdateManyInput>
  /**
   * Filter which Mitarbeiters to update
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * Limit how many Mitarbeiters to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Mitarbeiter upsert
 */
export type MitarbeiterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * The filter to search for the Mitarbeiter to update in case it exists.
   */
  where: Prisma.MitarbeiterWhereUniqueInput
  /**
   * In case the Mitarbeiter found by the `where` argument doesn't exist, create a new Mitarbeiter with this data.
   */
  create: Prisma.XOR<Prisma.MitarbeiterCreateInput, Prisma.MitarbeiterUncheckedCreateInput>
  /**
   * In case the Mitarbeiter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MitarbeiterUpdateInput, Prisma.MitarbeiterUncheckedUpdateInput>
}

/**
 * Mitarbeiter delete
 */
export type MitarbeiterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  /**
   * Filter which Mitarbeiter to delete.
   */
  where: Prisma.MitarbeiterWhereUniqueInput
}

/**
 * Mitarbeiter deleteMany
 */
export type MitarbeiterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mitarbeiters to delete
   */
  where?: Prisma.MitarbeiterWhereInput
  /**
   * Limit how many Mitarbeiters to delete.
   */
  limit?: number
}

/**
 * Mitarbeiter without action
 */
export type MitarbeiterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
}
