
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `InternalRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model InternalRequest
 * 
 */
export type InternalRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$InternalRequestPayload>

export type AggregateInternalRequest = {
  _count: InternalRequestCountAggregateOutputType | null
  _avg: InternalRequestAvgAggregateOutputType | null
  _sum: InternalRequestSumAggregateOutputType | null
  _min: InternalRequestMinAggregateOutputType | null
  _max: InternalRequestMaxAggregateOutputType | null
}

export type InternalRequestAvgAggregateOutputType = {
  floor: number | null
}

export type InternalRequestSumAggregateOutputType = {
  floor: number | null
}

export type InternalRequestMinAggregateOutputType = {
  id: string | null
  liftId: string | null
  floor: number | null
  createdAt: Date | null
}

export type InternalRequestMaxAggregateOutputType = {
  id: string | null
  liftId: string | null
  floor: number | null
  createdAt: Date | null
}

export type InternalRequestCountAggregateOutputType = {
  id: number
  liftId: number
  floor: number
  createdAt: number
  _all: number
}


export type InternalRequestAvgAggregateInputType = {
  floor?: true
}

export type InternalRequestSumAggregateInputType = {
  floor?: true
}

export type InternalRequestMinAggregateInputType = {
  id?: true
  liftId?: true
  floor?: true
  createdAt?: true
}

export type InternalRequestMaxAggregateInputType = {
  id?: true
  liftId?: true
  floor?: true
  createdAt?: true
}

export type InternalRequestCountAggregateInputType = {
  id?: true
  liftId?: true
  floor?: true
  createdAt?: true
  _all?: true
}

export type InternalRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InternalRequest to aggregate.
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InternalRequests to fetch.
   */
  orderBy?: Prisma.InternalRequestOrderByWithRelationInput | Prisma.InternalRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InternalRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InternalRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InternalRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InternalRequests
  **/
  _count?: true | InternalRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InternalRequestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InternalRequestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InternalRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InternalRequestMaxAggregateInputType
}

export type GetInternalRequestAggregateType<T extends InternalRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateInternalRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInternalRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateInternalRequest[P]>
}




export type InternalRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InternalRequestWhereInput
  orderBy?: Prisma.InternalRequestOrderByWithAggregationInput | Prisma.InternalRequestOrderByWithAggregationInput[]
  by: Prisma.InternalRequestScalarFieldEnum[] | Prisma.InternalRequestScalarFieldEnum
  having?: Prisma.InternalRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InternalRequestCountAggregateInputType | true
  _avg?: InternalRequestAvgAggregateInputType
  _sum?: InternalRequestSumAggregateInputType
  _min?: InternalRequestMinAggregateInputType
  _max?: InternalRequestMaxAggregateInputType
}

export type InternalRequestGroupByOutputType = {
  id: string
  liftId: string
  floor: number
  createdAt: Date
  _count: InternalRequestCountAggregateOutputType | null
  _avg: InternalRequestAvgAggregateOutputType | null
  _sum: InternalRequestSumAggregateOutputType | null
  _min: InternalRequestMinAggregateOutputType | null
  _max: InternalRequestMaxAggregateOutputType | null
}

type GetInternalRequestGroupByPayload<T extends InternalRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InternalRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InternalRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InternalRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InternalRequestGroupByOutputType[P]>
      }
    >
  >



export type InternalRequestWhereInput = {
  AND?: Prisma.InternalRequestWhereInput | Prisma.InternalRequestWhereInput[]
  OR?: Prisma.InternalRequestWhereInput[]
  NOT?: Prisma.InternalRequestWhereInput | Prisma.InternalRequestWhereInput[]
  id?: Prisma.StringFilter<"InternalRequest"> | string
  liftId?: Prisma.StringFilter<"InternalRequest"> | string
  floor?: Prisma.IntFilter<"InternalRequest"> | number
  createdAt?: Prisma.DateTimeFilter<"InternalRequest"> | Date | string
  Lift?: Prisma.XOR<Prisma.LiftScalarRelationFilter, Prisma.LiftWhereInput>
}

export type InternalRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  liftId?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  Lift?: Prisma.LiftOrderByWithRelationInput
}

export type InternalRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InternalRequestWhereInput | Prisma.InternalRequestWhereInput[]
  OR?: Prisma.InternalRequestWhereInput[]
  NOT?: Prisma.InternalRequestWhereInput | Prisma.InternalRequestWhereInput[]
  liftId?: Prisma.StringFilter<"InternalRequest"> | string
  floor?: Prisma.IntFilter<"InternalRequest"> | number
  createdAt?: Prisma.DateTimeFilter<"InternalRequest"> | Date | string
  Lift?: Prisma.XOR<Prisma.LiftScalarRelationFilter, Prisma.LiftWhereInput>
}, "id">

export type InternalRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  liftId?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.InternalRequestCountOrderByAggregateInput
  _avg?: Prisma.InternalRequestAvgOrderByAggregateInput
  _max?: Prisma.InternalRequestMaxOrderByAggregateInput
  _min?: Prisma.InternalRequestMinOrderByAggregateInput
  _sum?: Prisma.InternalRequestSumOrderByAggregateInput
}

export type InternalRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.InternalRequestScalarWhereWithAggregatesInput | Prisma.InternalRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.InternalRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InternalRequestScalarWhereWithAggregatesInput | Prisma.InternalRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InternalRequest"> | string
  liftId?: Prisma.StringWithAggregatesFilter<"InternalRequest"> | string
  floor?: Prisma.IntWithAggregatesFilter<"InternalRequest"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InternalRequest"> | Date | string
}

export type InternalRequestCreateInput = {
  id?: string
  floor: number
  createdAt?: Date | string
  Lift: Prisma.LiftCreateNestedOneWithoutInternalRequestsInput
}

export type InternalRequestUncheckedCreateInput = {
  id?: string
  liftId: string
  floor: number
  createdAt?: Date | string
}

export type InternalRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Lift?: Prisma.LiftUpdateOneRequiredWithoutInternalRequestsNestedInput
}

export type InternalRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  liftId?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InternalRequestCreateManyInput = {
  id?: string
  liftId: string
  floor: number
  createdAt?: Date | string
}

export type InternalRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InternalRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  liftId?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InternalRequestListRelationFilter = {
  every?: Prisma.InternalRequestWhereInput
  some?: Prisma.InternalRequestWhereInput
  none?: Prisma.InternalRequestWhereInput
}

export type InternalRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InternalRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  liftId?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InternalRequestAvgOrderByAggregateInput = {
  floor?: Prisma.SortOrder
}

export type InternalRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  liftId?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InternalRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  liftId?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InternalRequestSumOrderByAggregateInput = {
  floor?: Prisma.SortOrder
}

export type InternalRequestCreateNestedManyWithoutLiftInput = {
  create?: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput> | Prisma.InternalRequestCreateWithoutLiftInput[] | Prisma.InternalRequestUncheckedCreateWithoutLiftInput[]
  connectOrCreate?: Prisma.InternalRequestCreateOrConnectWithoutLiftInput | Prisma.InternalRequestCreateOrConnectWithoutLiftInput[]
  createMany?: Prisma.InternalRequestCreateManyLiftInputEnvelope
  connect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
}

export type InternalRequestUncheckedCreateNestedManyWithoutLiftInput = {
  create?: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput> | Prisma.InternalRequestCreateWithoutLiftInput[] | Prisma.InternalRequestUncheckedCreateWithoutLiftInput[]
  connectOrCreate?: Prisma.InternalRequestCreateOrConnectWithoutLiftInput | Prisma.InternalRequestCreateOrConnectWithoutLiftInput[]
  createMany?: Prisma.InternalRequestCreateManyLiftInputEnvelope
  connect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
}

export type InternalRequestUpdateManyWithoutLiftNestedInput = {
  create?: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput> | Prisma.InternalRequestCreateWithoutLiftInput[] | Prisma.InternalRequestUncheckedCreateWithoutLiftInput[]
  connectOrCreate?: Prisma.InternalRequestCreateOrConnectWithoutLiftInput | Prisma.InternalRequestCreateOrConnectWithoutLiftInput[]
  upsert?: Prisma.InternalRequestUpsertWithWhereUniqueWithoutLiftInput | Prisma.InternalRequestUpsertWithWhereUniqueWithoutLiftInput[]
  createMany?: Prisma.InternalRequestCreateManyLiftInputEnvelope
  set?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  disconnect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  delete?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  connect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  update?: Prisma.InternalRequestUpdateWithWhereUniqueWithoutLiftInput | Prisma.InternalRequestUpdateWithWhereUniqueWithoutLiftInput[]
  updateMany?: Prisma.InternalRequestUpdateManyWithWhereWithoutLiftInput | Prisma.InternalRequestUpdateManyWithWhereWithoutLiftInput[]
  deleteMany?: Prisma.InternalRequestScalarWhereInput | Prisma.InternalRequestScalarWhereInput[]
}

export type InternalRequestUncheckedUpdateManyWithoutLiftNestedInput = {
  create?: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput> | Prisma.InternalRequestCreateWithoutLiftInput[] | Prisma.InternalRequestUncheckedCreateWithoutLiftInput[]
  connectOrCreate?: Prisma.InternalRequestCreateOrConnectWithoutLiftInput | Prisma.InternalRequestCreateOrConnectWithoutLiftInput[]
  upsert?: Prisma.InternalRequestUpsertWithWhereUniqueWithoutLiftInput | Prisma.InternalRequestUpsertWithWhereUniqueWithoutLiftInput[]
  createMany?: Prisma.InternalRequestCreateManyLiftInputEnvelope
  set?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  disconnect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  delete?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  connect?: Prisma.InternalRequestWhereUniqueInput | Prisma.InternalRequestWhereUniqueInput[]
  update?: Prisma.InternalRequestUpdateWithWhereUniqueWithoutLiftInput | Prisma.InternalRequestUpdateWithWhereUniqueWithoutLiftInput[]
  updateMany?: Prisma.InternalRequestUpdateManyWithWhereWithoutLiftInput | Prisma.InternalRequestUpdateManyWithWhereWithoutLiftInput[]
  deleteMany?: Prisma.InternalRequestScalarWhereInput | Prisma.InternalRequestScalarWhereInput[]
}

export type InternalRequestCreateWithoutLiftInput = {
  id?: string
  floor: number
  createdAt?: Date | string
}

export type InternalRequestUncheckedCreateWithoutLiftInput = {
  id?: string
  floor: number
  createdAt?: Date | string
}

export type InternalRequestCreateOrConnectWithoutLiftInput = {
  where: Prisma.InternalRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput>
}

export type InternalRequestCreateManyLiftInputEnvelope = {
  data: Prisma.InternalRequestCreateManyLiftInput | Prisma.InternalRequestCreateManyLiftInput[]
}

export type InternalRequestUpsertWithWhereUniqueWithoutLiftInput = {
  where: Prisma.InternalRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.InternalRequestUpdateWithoutLiftInput, Prisma.InternalRequestUncheckedUpdateWithoutLiftInput>
  create: Prisma.XOR<Prisma.InternalRequestCreateWithoutLiftInput, Prisma.InternalRequestUncheckedCreateWithoutLiftInput>
}

export type InternalRequestUpdateWithWhereUniqueWithoutLiftInput = {
  where: Prisma.InternalRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.InternalRequestUpdateWithoutLiftInput, Prisma.InternalRequestUncheckedUpdateWithoutLiftInput>
}

export type InternalRequestUpdateManyWithWhereWithoutLiftInput = {
  where: Prisma.InternalRequestScalarWhereInput
  data: Prisma.XOR<Prisma.InternalRequestUpdateManyMutationInput, Prisma.InternalRequestUncheckedUpdateManyWithoutLiftInput>
}

export type InternalRequestScalarWhereInput = {
  AND?: Prisma.InternalRequestScalarWhereInput | Prisma.InternalRequestScalarWhereInput[]
  OR?: Prisma.InternalRequestScalarWhereInput[]
  NOT?: Prisma.InternalRequestScalarWhereInput | Prisma.InternalRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"InternalRequest"> | string
  liftId?: Prisma.StringFilter<"InternalRequest"> | string
  floor?: Prisma.IntFilter<"InternalRequest"> | number
  createdAt?: Prisma.DateTimeFilter<"InternalRequest"> | Date | string
}

export type InternalRequestCreateManyLiftInput = {
  id?: string
  floor: number
  createdAt?: Date | string
}

export type InternalRequestUpdateWithoutLiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InternalRequestUncheckedUpdateWithoutLiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InternalRequestUncheckedUpdateManyWithoutLiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  floor?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InternalRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  liftId?: boolean
  floor?: boolean
  createdAt?: boolean
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}, ExtArgs["result"]["internalRequest"]>

export type InternalRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  liftId?: boolean
  floor?: boolean
  createdAt?: boolean
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}, ExtArgs["result"]["internalRequest"]>

export type InternalRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  liftId?: boolean
  floor?: boolean
  createdAt?: boolean
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}, ExtArgs["result"]["internalRequest"]>

export type InternalRequestSelectScalar = {
  id?: boolean
  liftId?: boolean
  floor?: boolean
  createdAt?: boolean
}

export type InternalRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "liftId" | "floor" | "createdAt", ExtArgs["result"]["internalRequest"]>
export type InternalRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}
export type InternalRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}
export type InternalRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Lift?: boolean | Prisma.LiftDefaultArgs<ExtArgs>
}

export type $InternalRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InternalRequest"
  objects: {
    Lift: Prisma.$LiftPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    liftId: string
    floor: number
    createdAt: Date
  }, ExtArgs["result"]["internalRequest"]>
  composites: {}
}

export type InternalRequestGetPayload<S extends boolean | null | undefined | InternalRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload, S>

export type InternalRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InternalRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InternalRequestCountAggregateInputType | true
  }

export interface InternalRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InternalRequest'], meta: { name: 'InternalRequest' } }
  /**
   * Find zero or one InternalRequest that matches the filter.
   * @param {InternalRequestFindUniqueArgs} args - Arguments to find a InternalRequest
   * @example
   * // Get one InternalRequest
   * const internalRequest = await prisma.internalRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InternalRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, InternalRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InternalRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InternalRequestFindUniqueOrThrowArgs} args - Arguments to find a InternalRequest
   * @example
   * // Get one InternalRequest
   * const internalRequest = await prisma.internalRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InternalRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InternalRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InternalRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestFindFirstArgs} args - Arguments to find a InternalRequest
   * @example
   * // Get one InternalRequest
   * const internalRequest = await prisma.internalRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InternalRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, InternalRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InternalRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestFindFirstOrThrowArgs} args - Arguments to find a InternalRequest
   * @example
   * // Get one InternalRequest
   * const internalRequest = await prisma.internalRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InternalRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InternalRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InternalRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InternalRequests
   * const internalRequests = await prisma.internalRequest.findMany()
   * 
   * // Get first 10 InternalRequests
   * const internalRequests = await prisma.internalRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const internalRequestWithIdOnly = await prisma.internalRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InternalRequestFindManyArgs>(args?: Prisma.SelectSubset<T, InternalRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InternalRequest.
   * @param {InternalRequestCreateArgs} args - Arguments to create a InternalRequest.
   * @example
   * // Create one InternalRequest
   * const InternalRequest = await prisma.internalRequest.create({
   *   data: {
   *     // ... data to create a InternalRequest
   *   }
   * })
   * 
   */
  create<T extends InternalRequestCreateArgs>(args: Prisma.SelectSubset<T, InternalRequestCreateArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InternalRequests.
   * @param {InternalRequestCreateManyArgs} args - Arguments to create many InternalRequests.
   * @example
   * // Create many InternalRequests
   * const internalRequest = await prisma.internalRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InternalRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, InternalRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InternalRequests and returns the data saved in the database.
   * @param {InternalRequestCreateManyAndReturnArgs} args - Arguments to create many InternalRequests.
   * @example
   * // Create many InternalRequests
   * const internalRequest = await prisma.internalRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InternalRequests and only return the `id`
   * const internalRequestWithIdOnly = await prisma.internalRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InternalRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InternalRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InternalRequest.
   * @param {InternalRequestDeleteArgs} args - Arguments to delete one InternalRequest.
   * @example
   * // Delete one InternalRequest
   * const InternalRequest = await prisma.internalRequest.delete({
   *   where: {
   *     // ... filter to delete one InternalRequest
   *   }
   * })
   * 
   */
  delete<T extends InternalRequestDeleteArgs>(args: Prisma.SelectSubset<T, InternalRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InternalRequest.
   * @param {InternalRequestUpdateArgs} args - Arguments to update one InternalRequest.
   * @example
   * // Update one InternalRequest
   * const internalRequest = await prisma.internalRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InternalRequestUpdateArgs>(args: Prisma.SelectSubset<T, InternalRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InternalRequests.
   * @param {InternalRequestDeleteManyArgs} args - Arguments to filter InternalRequests to delete.
   * @example
   * // Delete a few InternalRequests
   * const { count } = await prisma.internalRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InternalRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, InternalRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InternalRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InternalRequests
   * const internalRequest = await prisma.internalRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InternalRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, InternalRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InternalRequests and returns the data updated in the database.
   * @param {InternalRequestUpdateManyAndReturnArgs} args - Arguments to update many InternalRequests.
   * @example
   * // Update many InternalRequests
   * const internalRequest = await prisma.internalRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InternalRequests and only return the `id`
   * const internalRequestWithIdOnly = await prisma.internalRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InternalRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InternalRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InternalRequest.
   * @param {InternalRequestUpsertArgs} args - Arguments to update or create a InternalRequest.
   * @example
   * // Update or create a InternalRequest
   * const internalRequest = await prisma.internalRequest.upsert({
   *   create: {
   *     // ... data to create a InternalRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InternalRequest we want to update
   *   }
   * })
   */
  upsert<T extends InternalRequestUpsertArgs>(args: Prisma.SelectSubset<T, InternalRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__InternalRequestClient<runtime.Types.Result.GetResult<Prisma.$InternalRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InternalRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestCountArgs} args - Arguments to filter InternalRequests to count.
   * @example
   * // Count the number of InternalRequests
   * const count = await prisma.internalRequest.count({
   *   where: {
   *     // ... the filter for the InternalRequests we want to count
   *   }
   * })
  **/
  count<T extends InternalRequestCountArgs>(
    args?: Prisma.Subset<T, InternalRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InternalRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InternalRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InternalRequestAggregateArgs>(args: Prisma.Subset<T, InternalRequestAggregateArgs>): Prisma.PrismaPromise<GetInternalRequestAggregateType<T>>

  /**
   * Group by InternalRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InternalRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InternalRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InternalRequestGroupByArgs['orderBy'] }
      : { orderBy?: InternalRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InternalRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInternalRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InternalRequest model
 */
readonly fields: InternalRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InternalRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InternalRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Lift<T extends Prisma.LiftDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LiftDefaultArgs<ExtArgs>>): Prisma.Prisma__LiftClient<runtime.Types.Result.GetResult<Prisma.$LiftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InternalRequest model
 */
export interface InternalRequestFieldRefs {
  readonly id: Prisma.FieldRef<"InternalRequest", 'String'>
  readonly liftId: Prisma.FieldRef<"InternalRequest", 'String'>
  readonly floor: Prisma.FieldRef<"InternalRequest", 'Int'>
  readonly createdAt: Prisma.FieldRef<"InternalRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InternalRequest findUnique
 */
export type InternalRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter, which InternalRequest to fetch.
   */
  where: Prisma.InternalRequestWhereUniqueInput
}

/**
 * InternalRequest findUniqueOrThrow
 */
export type InternalRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter, which InternalRequest to fetch.
   */
  where: Prisma.InternalRequestWhereUniqueInput
}

/**
 * InternalRequest findFirst
 */
export type InternalRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter, which InternalRequest to fetch.
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InternalRequests to fetch.
   */
  orderBy?: Prisma.InternalRequestOrderByWithRelationInput | Prisma.InternalRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InternalRequests.
   */
  cursor?: Prisma.InternalRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InternalRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InternalRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InternalRequests.
   */
  distinct?: Prisma.InternalRequestScalarFieldEnum | Prisma.InternalRequestScalarFieldEnum[]
}

/**
 * InternalRequest findFirstOrThrow
 */
export type InternalRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter, which InternalRequest to fetch.
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InternalRequests to fetch.
   */
  orderBy?: Prisma.InternalRequestOrderByWithRelationInput | Prisma.InternalRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InternalRequests.
   */
  cursor?: Prisma.InternalRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InternalRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InternalRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InternalRequests.
   */
  distinct?: Prisma.InternalRequestScalarFieldEnum | Prisma.InternalRequestScalarFieldEnum[]
}

/**
 * InternalRequest findMany
 */
export type InternalRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter, which InternalRequests to fetch.
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InternalRequests to fetch.
   */
  orderBy?: Prisma.InternalRequestOrderByWithRelationInput | Prisma.InternalRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InternalRequests.
   */
  cursor?: Prisma.InternalRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InternalRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InternalRequests.
   */
  skip?: number
  distinct?: Prisma.InternalRequestScalarFieldEnum | Prisma.InternalRequestScalarFieldEnum[]
}

/**
 * InternalRequest create
 */
export type InternalRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a InternalRequest.
   */
  data: Prisma.XOR<Prisma.InternalRequestCreateInput, Prisma.InternalRequestUncheckedCreateInput>
}

/**
 * InternalRequest createMany
 */
export type InternalRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InternalRequests.
   */
  data: Prisma.InternalRequestCreateManyInput | Prisma.InternalRequestCreateManyInput[]
}

/**
 * InternalRequest createManyAndReturn
 */
export type InternalRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * The data used to create many InternalRequests.
   */
  data: Prisma.InternalRequestCreateManyInput | Prisma.InternalRequestCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InternalRequest update
 */
export type InternalRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a InternalRequest.
   */
  data: Prisma.XOR<Prisma.InternalRequestUpdateInput, Prisma.InternalRequestUncheckedUpdateInput>
  /**
   * Choose, which InternalRequest to update.
   */
  where: Prisma.InternalRequestWhereUniqueInput
}

/**
 * InternalRequest updateMany
 */
export type InternalRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InternalRequests.
   */
  data: Prisma.XOR<Prisma.InternalRequestUpdateManyMutationInput, Prisma.InternalRequestUncheckedUpdateManyInput>
  /**
   * Filter which InternalRequests to update
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * Limit how many InternalRequests to update.
   */
  limit?: number
}

/**
 * InternalRequest updateManyAndReturn
 */
export type InternalRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * The data used to update InternalRequests.
   */
  data: Prisma.XOR<Prisma.InternalRequestUpdateManyMutationInput, Prisma.InternalRequestUncheckedUpdateManyInput>
  /**
   * Filter which InternalRequests to update
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * Limit how many InternalRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InternalRequest upsert
 */
export type InternalRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the InternalRequest to update in case it exists.
   */
  where: Prisma.InternalRequestWhereUniqueInput
  /**
   * In case the InternalRequest found by the `where` argument doesn't exist, create a new InternalRequest with this data.
   */
  create: Prisma.XOR<Prisma.InternalRequestCreateInput, Prisma.InternalRequestUncheckedCreateInput>
  /**
   * In case the InternalRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InternalRequestUpdateInput, Prisma.InternalRequestUncheckedUpdateInput>
}

/**
 * InternalRequest delete
 */
export type InternalRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
  /**
   * Filter which InternalRequest to delete.
   */
  where: Prisma.InternalRequestWhereUniqueInput
}

/**
 * InternalRequest deleteMany
 */
export type InternalRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InternalRequests to delete
   */
  where?: Prisma.InternalRequestWhereInput
  /**
   * Limit how many InternalRequests to delete.
   */
  limit?: number
}

/**
 * InternalRequest without action
 */
export type InternalRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InternalRequest
   */
  select?: Prisma.InternalRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InternalRequest
   */
  omit?: Prisma.InternalRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InternalRequestInclude<ExtArgs> | null
}
